### ISSUE TITLE
直接使用 window.onscroll = func 的话 那么我这个事件的其他方法执行了

### ISSUE THREAD

**Issue by notbucai** [whidy/infinite-scroll-vuejs#2]
直接使用 window.onscroll = func 的话 那么我这个事件的其他方法执行了，但是如果用addEventListener话应该在什么时候对事件进行移除

**Comment by whidy** [comment]
不建议用window.onscroll，

如果这个func离开组件后就不使用了，可以直接在beforeDestroy时移除

同样的也可以在beforeDestroy，removeEventListener

**Comment by notbucai** [comment]
好的谢谢
